services:
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env # Use environment variables from .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./postgres-schema.sql:/docker-entrypoint-initdb.d/init.sql  # Mount your SQL script
    environment:
      POSTGRES_DB: ${POSTGRES_DB}   # These values should be defined in your .env file
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    env_file:
      - .env
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
